name: Build Design System package

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ZeroGachis'

      # Skip post-install scripts here, as a malicious
      # script could steal GITHUB_TOKEN.
      - name: Install dependencies
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # `npm rebuild` will run all those post-install scripts for us.
      - name: Rebuild & Prepare dependencies
        run: npm rebuild && npm run prepare --if-present

      - name: Update package version
        run: npm version --no-git-tag-version ${{ github.ref_name }}

      - name: Compile
        run: npm run tsc

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: True
