name: Publish package

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: [self-hosted, debian-stable]
        steps:
            - name: Clean Workspace
              uses: mickem/clean-after-action@v1
            - name: Checkout
              uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@ZeroGachis'
            # Skip post-install scripts here, as a malicious
            # script could steal GITHUB_TOKEN.
            - name: Install dependencies
              run: npm ci --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # `npm rebuild` will run all those post-install scripts for us.
            - name: Rebuild & Prepare dependencies
              run: npm rebuild && npm run prepare --if-present
            - name: Compile
              run: npm run tsc
            - name: Publish to Github Registry
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
