name: Security Scan Repo

on:
  push:
    branches:
      - main
      - master
      - develop
      - tools
      - release/*
  schedule:
    - cron: "0 10 * * 1"

permissions:
  contents: read
  pull-requests: write
  security-events: write
  checks: write
  actions: read

jobs:
  security_scan:
    uses: ZeroGachis/.github/.github/workflows/security_scan_repo.yml@v4
    secrets: inherit
